eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: RibbonConsumerClient
    api-b:
      path: /api-b/**
      serviceId: NumberClient
  host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000
logging:
  file: ${spring.application.name}.log
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000