eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: feignSayHiClient
logging:
  file: ${spring.application.name}.log